### PR TITLE
Jump fix

### PR DESCRIPTION
**Pull request by IAFahim**
You forgot to add ground tag to all floors:

https://github.com/user-attachments/assets/13202c9e-424f-444c-9d81-2aa8a0b7d7ec

Bushra is too heavy naa and you were giving her only 1 newton force up. So she couldn't jump. I gave him the same force as gravity but negative so he can just jump for a few seconds.

image

### CODE REVIEW

**Comment by IAFahim** [comment]
Also removed the sorting layer stuff it gets complicated so removed it.

**Comment by IAFahim** [comment]
300 Taka Please.

**Comment by BushraOnika** [comment]
> 300 Taka Please.

Cut from salaryy

**Comment by IAFahim** [comment]
You you don't have a salary 🙂 You don't pay attention to text or conversation huh 😑 need to give pittiy treatment 😐

You don't get monthly salary you get monthly lone. After the first salary. I told you, you need to earn by helping me for 300 BDT for per brunch commit. And i was paying you money so that parents don't start asking questions why aren't you getting money. You have to earn by helping me and currently you owe me 10100 BDT from fine only.

**Comment by BushraOnika** [comment]
Ok no money from next month will do thr work then cut from there your 10k

**Comment by BushraOnika** [comment]
Btw how it becomes 10k?! 🙂 
You reduced 300 bdt na

**Comment by IAFahim** [comment]
> Ok no money from next month will do thr work then cut from there your 10k

You would still be getting 5k and have to work hard so that you can claim those 5k huh

**Comment by IAFahim** [comment]
> Btw how it becomes 10k?! 🙂
You reduced 300 bdt na

My god, you didn't pay any attention

Okay, so it was 5400 BDT beacuse of fine + 5000 BDT for last month.
But you used to push commit and i was just giving you advance on your work. Which you didn't do any yet.

**Comment by BushraOnika** [comment]
No need of 5k loan again thank you I'm happy with 0 bdt then negative 10k🙂

**Comment by BushraOnika** [comment]
You should give me some lessons how to make islands then I can cause I'm not finding any tutorial for island makes so how would I do if you teach me one then I can make 100 without knowledge how would I make🙂 😑😑😑

**Comment by IAFahim** [comment]
> No need of 5k loan again thank you I'm happy with 0 bdt then negative 10k

Your parents would give boka, not allowed

**Comment by IAFahim** [comment]
> You should give me some lessons how to make islands then I can cause I'm not finding any tutorial for island makes so how would I do if you teach me one then I can make 100 without knowledge how would I make🙂 😑😑😑

I was thinking 2 whole day how to trap you so that i get to teach you a lot and you get very smart.
And now you are asking from yourself 😌😏 you are cooked. From not one till your August deployment. You would have do class from 8 am to 12 pm every Sunday, Tuesday, Thursday. 1h class every 2h.

**Comment by IAFahim** [comment]
So nice of you coming and asking your self and getting caught. 
I give you 10 out of 10. Osthir. Mashallah. Ato valo. Wow. Awesome.
And I can just say that it's punishment for you asking. Wow magic.

**Comment by BushraOnika** [comment]
> > No need of 5k loan again thank you I'm happy with 0 bdt then negative 10k
> 
> Your parents would give boka, not allowed

No they won't say anything I need those for Tintin treatment but he is not around now so I don't need any money

**Comment by BushraOnika** [comment]
> > You should give me some lessons how to make islands then I can cause I'm not finding any tutorial for island makes so how would I do if you teach me one then I can make 100 without knowledge how would I make🙂 😑😑😑
> 
> I was thinking 2 whole day how to trap you so that i get to teach you a lot and you get very smart. And now you are asking from yourself 😌😏 you are cooked. From not one till your August deployment. You would have do class from 8 am to 12 pm every Sunday, Tuesday, Thursday. 1h class every 2h.

Why 1H class in every 2h give it gives so much pressure🙂🙂

**Comment by IAFahim** [comment]
> No they won't say anything I need those for Tintin treatment but he is not around now so I don't need any money

Tintin would be back Inshallah. And you would be all angry for me making you worry, huh, Shouldn't give up hope at all.

**Comment by IAFahim** [comment]
> Why 1H class in every 2h give it gives so much pressure🙂🙂

What kind of pressure. Please explain. So that I can make it more suitable

**Comment by BushraOnika** [comment]
Like I have to concentrate in IELTS also in the evening so ¯\🙄/¯
And I had to do other works of home na so before I finished work it's time for the the class comes🙂
So make it a fixed time 🙂

**Comment by IAFahim** [comment]
You do housework?? I thought you were the princess of the house. Ehh and I made fun of you so much and you never corrected.

Okay every 4 hour every day other than Friday and Saturday. 

8:00am - 9:00am
11.30 am - 12.30pm
2:45pm - 3:45pm
8:00pm - 9:00pm
12:00pm - 1:00am

**Comment by BushraOnika** [comment]
I just don't care whatever anyone thinks of me so I don't correct anyone btw.. Whatever anyone wish they can assume and think I don't mind at all🤦‍♀️

**Comment by BushraOnika** [comment]
> You do housework?? I thought you were the princess of the house. Ehh and I made fun of you so much and you never corrected.
> 
> Okay every 4 hour every day other than Friday and Saturday.
> 
> 8:00am - 9:00am 11.30 am - 12.30pm 3:00pm - 4:00pm 7:00pm - 8:00pm 12:00pm - 1:00am

Sunday Tuesday and Thursday right??? 😐👀

**Comment by IAFahim** [comment]
> I just don't care whatever anyone thinks of me so I don't correct anyone btw.. Whatever anyone wish they can assume and think I don't mind at all🤦‍♀️

Ehh, they how would people know if they are correct or not 🥺 should they ask you if what they are thinking is correct or not?

**Comment by IAFahim** [comment]
> Sunday Tuesday and Thursday right??? 😐👀

Yes, those days are included. See I reduced to every 4h and days also.

**Comment by IAFahim** [comment]
See you at morning

**Comment by IAFahim** [comment]
Join:
https://us04web.zoom.us/j/71091567845?pwd=IvjbrVKX8AotP6KvCrJAUy0XCNQGD8.1

**Comment by IAFahim** [comment]
come come

**Comment by BushraOnika** [comment]
Oma it started from today you didn't inform I thought from next week 🙈

**Comment by IAFahim** [comment]
Every time on class hour electric goes away. How are you controlling it. You have supa power too 🥲.

**Comment by IAFahim** [comment]
Have to give boka, you didn't know about no electricity problem so you are late. You have to answer 2 question about you, huh. For not coming to 2 classes. Ignoring not allowed

**Comment by BushraOnika** [comment]
> Every time on class hour electric goes away. How are you controlling it. You have supa power too 🥲.

Wowww electricity also wants me to do class from next week yee yeee😍

**Comment by IAFahim** [comment]
You have class at 8 pm. I need to come back from prayer so changed time a little bit

**Comment by IAFahim** [comment]
Rude huh, everyone loves you not fair

**Comment by IAFahim** [comment]
Join
https://us04web.zoom.us/j/72140088827?pwd=7pqHJXKKwNDchwa0Xei8nBJNPLRDaL.1

**Comment by BushraOnika** [comment]
Ehhh I missed to see the text 🙂

**Comment by BushraOnika** [comment]
It doesn't give any mail so I don't get any notification 🙂

**Comment by IAFahim** [comment]
Good good, my notification can disturb you huh. Next class starts at 12am till 1am. You owe me 3 questions now.

**Comment by BushraOnika** [comment]
Make it 12.15am will alarm 🙂

**Comment by IAFahim** [comment]
Okay

**Comment by IAFahim** [comment]
This is my permanent zoom link when ever you are stuck or need any help you can join. Ow its time for class also

https://us04web.zoom.us/launch/chat?src=direct_chat_link&email=fahimmanowarj5%40gmail.com

**Comment by BushraOnika** [comment]
How to join with phone🙂 can't join see see I'm on time

**Comment by IAFahim** [comment]
Get on PC huh. You have to do work too

**Comment by IAFahim** [comment]
Thank you for setting alarm and also coming on time

**Comment by IAFahim** [comment]
https://us04web.zoom.us/j/79951658484?pwd=2tDXrj5nBvYl5KNi3Nf3s0fsqbVZZq.1

**Comment by BushraOnika** [comment]
Did you givve chutii ??? 
Tataaa wiil see you next class dayyy😶

**Comment by IAFahim** [comment]
Link

https://us04web.zoom.us/j/75592584366?pwd=gh43bJnbyJYBTrW0SaIOXUxHewouN1.1

**Comment by IAFahim** [comment]
See you tomorrow. Sorry for doing bokor bokor

**Comment by IAFahim** [comment]
PRO_GrAMmER PRO_GrAMmER is inviting you to a scheduled Zoom meeting.

Topic: PRO_GrAMmER PRO_GrAMmER's Personal Meeting Room
Join Zoom Meeting
https://us04web.zoom.us/j/7737772702?pwd=sIEuVz5pb0wjw2t5bNOkNA2904r5rR.1

Meeting ID: 773 777 2702
Passcode: G97wuQ

**Comment by IAFahim** [comment]
Did you try joining and couldn't connect? I tried a different link

**Comment by IAFahim** [comment]
Are you angry?
See you you tell me to get married, but its you who should huh. All friends in your life were stupid, always goes away. If gey married you would have someone who would say with you for ever and you can have kids and his family. You love people right? See people.

You know people tell others suggestions because they know a good thing. Friend might leave because there they aren't connected to your life that's why maybe.

**Comment by BushraOnika** [comment]
Sorry I forgot to alarn and couldn't wake up😅

**Comment by IAFahim** [comment]
Yess one more question

**Comment by IAFahim** [comment]
Can you come at 3 pm?

**Comment by IAFahim** [comment]
> Sorry I forgot to alarn and couldn't wake up😅

And your alarm likes me. Huh electric girl.

**Comment by BushraOnika** [comment]
> Can you come at 3 pm?

Ok

**Comment by BushraOnika** [comment]
Can you make it after asor or magrib?? 😐
I have some works which didn't finished yet

**Comment by IAFahim** [comment]
At 5:45pm Okay?

**Comment by IAFahim** [comment]
> Can you make it after asor or magrib?? 😐 I have some works which didn't finished yet

My god you are being considerate and letting me know! Are you okay? Sohori thik? Mashallah

**Comment by BushraOnika** [comment]
I always let you know huh
Just that I was not aware of tomorrow classes or just forgot so couldn't inform huh. 
I'm always good good💯
Yes yes 5.45 is ok okkk

**Comment by IAFahim** [comment]
>  always let you know huh

Tai? Then you are amazing. Not pocha at all.

> I'm always good good💯

Yes baba yes, you are.

**Comment by IAFahim** [comment]
Join 
https://us04web.zoom.us/j/7737772702?pwd=sIEuVz5pb0wjw2t5bNOkNA2904r5rR.1

**Comment by IAFahim** [comment]
https://meet.google.com/yti-ipci-hik

**Comment by IAFahim** [comment]
Join Join

**Comment by IAFahim** [comment]
You busy?

**Comment by IAFahim** [comment]
Angry??

**Comment by IAFahim** [comment]
Ehh might be gone. We will talk in next class Ishallah. Can you come 12:45 am?

**Comment by BushraOnika** [comment]
O sorry sorry electricity was gone

**Comment by BushraOnika** [comment]
> Ehh might be gone. We will talk in next class Ishallah. Can you come 12:45 am?


Yes yes free

**Comment by IAFahim** [comment]
Ehh i mean 12:15 am

**Comment by BushraOnika** [comment]
Ok no problem make it 12.00am
No problem

**Comment by BushraOnika** [comment]
Where whereee???

**Comment by IAFahim** [comment]
Coming

**Comment by IAFahim** [comment]
https://us04web.zoom.us/j/7737772702?pwd=sIEuVz5pb0wjw2t5bNOkNA2904r5rR.1

**Comment by IAFahim** [comment]
> Ok no problem make it 12.00am No problem

I was away and didn't thought you might have changed the time

**Comment by BushraOnika** [comment]
Oma you cut

**Comment by IAFahim** [comment]
No zoom limit over

**Comment by IAFahim** [comment]
https://meet.google.com/enf-hnzx-tfd

**Comment by IAFahim** [comment]
Join join

**Comment by IAFahim** [comment]
Electricity just went out

**Comment by IAFahim** [comment]
Join
https://discord.gg/D4Ge6fvx

**Comment by IAFahim** [comment]
Is everything okay? Are you asleep?

**Comment by BushraOnika** [comment]
I tried alot to wake up but couldn't 🌚

**Comment by BushraOnika** [comment]
The link is not working~~

**Comment by IAFahim** [comment]
Try this one 
https://discord.gg/MP9xKFZq

**Comment by IAFahim** [comment]
Onika come to Discord

**Comment by IAFahim** [comment]
Come come. I lost track of time little

**Comment by IAFahim** [comment]
Super sorry

**Comment by IAFahim** [comment]
I was eating fish so couldn't hurry, also I was watching a video. But got mixed up and I forgot about time. I was remembering time is up 30 mins ago and doing stuff quick quick. But forgot while eating. Onek sorry, forgive me naa.

**Comment by IAFahim** [comment]
Which floor and room number is Sir's?
Discord mic wasn't working. I was talking but didn't work at all

**Comment by IAFahim** [comment]
Don't be angry at me for talking with all your friends.
I have heard people are an average of 5 people around them. So if I got to know people who you talk with, I can understand the person life and what they go through daily better. So I spent so much time. Plus you were looking really nice and can't let your husband not get a good look of course 😌Thank you for telling me where you were. I thought I was brilliant enough to find you on my own. But couldn't find at, looked all over. So you helped a lot. Ow, ow and sorry that I told you didn't help, while he was trying to give job offer. You of course tried your super best. You might be busy doing IELTS prep. Good Good. Ow wait you are typing on discord.

**Comment by IAFahim** [comment]
Are you okay? Were you tired last night and fell asleep?

**Pull request merged**
